name: Lighthouse CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          uploadArtifacts: true
          temporaryPublicStorage: true
          configPath: './lighthouse.config.js'
          collect:
            startServerCommand: 'npm run start'
            url: ['http://localhost:3000']
            numberOfRuns: 3
          assert:
            assertions:
              'categories:best-practices': ['warn', {minScore: 0.83}]
              'categories:performance': ['error', {minScore: 0.9}]
              'categories:accessibility': ['error', {minScore: 0.9}]
              'categories:seo': ['error', {minScore: 0.9}] 